name: g4music
base: core22
adopt-info: g4music
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
    
slots:
  g4music:
    interface: dbus
    bus: session
    name: com.github.neithern.g4music
  mpris:
    name: G4Music
    
apps:
  g4music:
    command: usr/bin/g4music
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - network
      - network-status
      - raw-usb
      - optical-drive
      - removable-media
    slots:
      - mpris
    common-id: com.github.neithern.g4music
    desktop: usr/share/applications/com.github.neithern.g4music.desktop
    
parts:  
  g4music:
    source: https://gitlab.gnome.org/neithern/g4music.git
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.neithern.g4music.appdata.xml]
    meson-parameters:
      - -Dprefix=/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    build-packages:
      - build-essential
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    override-build: |
      sed -i '0,/APPLICATION_ID.to_string()/{s/APPLICATION_ID.to_string()/"G4Music".to_string()/}' ../src/src/audio/mpris_controller.rs
      craftctl default
  
